In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import openpyxl as ox
from transliterate import translit

file = r"C:\Users\aleksandrov.vd\Documents\Передвижки\Передвижка 22\2022\Исходник.xlsx"
df =  pd.read_excel(file, sheet_name="Лист1", index_col=0)
df.head()

,ОКТМО,Тип ТС,Категория ТС,Экологический класс,Вид топлива,Количество ТС,Население территории,CO,NOx,C,SO2,CH4,ЛОСНМ,NH3,Всего,ФО,Регион,Город,Источник
№пп,,,,,,,,,,,,,,,,,,,
1.0,1000.0,Легковые,M1,Евро 0,Б,409925.0,<= 1 млн,119.042220,13.773480,0.0,0.122978,0.262352,20.643823,0.013118,153.857970,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
2.0,1000.0,Легковые,M1,Евро 1,Б,5200.0,<= 1 млн,0.500240,0.078000,0.0,0.001425,0.001092,0.023348,0.005824,0.609929,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
3.0,1000.0,Легковые,M1,Евро 2,Б,62079.0,<= 1 млн,4.084798,0.365025,0.0,0.017010,0.009933,0.057113,0.094360,4.628238,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
4.0,1000.0,Легковые,M1,Евро 3,Б,75546.0,<= 1 млн,3.036949,0.178289,0.0,0.019491,0.004835,0.042004,0.090655,3.372222,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
5.0,1000.0,Легковые,M1,Евро 4,Б,163838.0,<= 1 млн,0.688120,0.219543,0.0,0.042270,0.007864,0.034734,0.157284,1.149815,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16

In [2]:
# Словарь по заменам 
# словарь можно заменить на распознавание похожих символов. (один список находит соответствие из другого по совпадающим символам
# это уберет вероятность появления новых ошибок

In [3]:
change = {
"Москва":"гор. Москва",
"Санкт-Петербург":"гор. Санкт-Петербург",
"Ненецкий АО":"Ненецкий автономный округ",
"Краснодарский Край":"Краснодарский край",
"Республика Адыгея":"Республика Адыгея (Адыгея)",
"г. Севастополь":"гор. Севастополь",
"Республика Северная Осетия-Алания":"Республика Северная Осетия - Алания",
"Республика Татарстан":"Республика Татарстан (Татарстан)",
"Чувашская Республика":"Чувашская Республика - Чувашия",
"Ханты-Мансийский автономный округ – Югра":"Ханты-Мансийский автономный округ - Югра",
"Кемеровская область":"Кемеровская область - Кузбасс",
"Краснодарский Край  ":"Краснодарский Край",
"Северо-Кавказский федеральный округ":"Северо–Кавказский федеральный округ",
"Кабардино-Балкарская республика": 'Кабардино-Балкарская Республика',
"Карачаево-Черкесская республика": 'Карачаево-Черкесская Республика',
"Чеченская республика": "Чеченская Республика"
}

In [4]:
#библиотека удобная чтобы заменять похожие символы H (лат) на Н (кир.), например
from transliterate.base import TranslitLanguagePack, registry

class ExampleLanguagePack(TranslitLanguagePack):
    language_code = "ruen"
    language_name = "ruen"
    mapping = (
        u"АВЕКМНОРСТУХ",
        u"ABEKMHOPCTYХ",
    )

registry.register(ExampleLanguagePack);

In [5]:
df["Категория ТС"].unique()
df = df.drop(columns = ["ОКТМО", 'Количество ТС'])

In [6]:
df

,Тип ТС,Категория ТС,Экологический класс,Вид топлива,Население территории,CO,NOx,C,SO2,CH4,ЛОСНМ,NH3,Всего,ФО,Регион,Город,Источник
№пп,,,,,,,,,,,,,,,,,
1.0,Легковые,M1,Евро 0,Б,<= 1 млн,119.042220,13.773480,0.000000,0.122978,0.262352,20.643823,0.013118,153.857970,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
2.0,Легковые,M1,Евро 1,Б,<= 1 млн,0.500240,0.078000,0.000000,0.001425,0.001092,0.023348,0.005824,0.609929,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
3.0,Легковые,M1,Евро 2,Б,<= 1 млн,4.084798,0.365025,0.000000,0.017010,0.009933,0.057113,0.094360,4.628238,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
4.0,Легковые,M1,Евро 3,Б,<= 1 млн,3.036949,0.178289,0.000000,0.019491,0.004835,0.042004,0.090655,3.372222,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
5.0,Легковые,M1,Евро 4,Б,<= 1 млн,0.688120,0.219543,0.000000,0.042270,0.007864,0.034734,0.157284,1.149815,Сибирский ФО,Алтайский край,NaN,Таблица 10 Таблица 16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11086.0,Автобусы,M3,Евро 2,ДТ,<= 1 млн,0.005250,0.019950,0.001338,0.000539,0.000016,0.003884,0.000008,0.030985,Дальневосточный ФО,Еврейская автономная область,NaN,Таблица 15 Таблица 21
11087.0,Автобусы,M3,Евро 3,ДТ,<= 1 млн,0.008918,0.034075,0.001414,0.001238,0.000013,0.003793,0.000020,0.049470,Дальневосточный ФО,Еврейская автономная область,NaN,Таблица 15 Таблица 21
11088.0,Автобусы,M3,Евро 4,ДТ,<= 1 млн,0.004156,0.015817,0.000204,0.000811,0.000004,0.000331,0.000013,0.021337,Дальневосточный ФО,Еврейская автономная область,NaN,Таблица 15 Таблица 21
11089.0,Автобусы,M3,Евро 5,ДТ,<= 1 млн,0.003106,0.006993,0.000153,0.000606,0.000003,0.000247,0.000010,0.011118,Дальневосточный ФО,Еврейская автономная область,NaN,Таблица 15 Таблица 21
NaN,NaN,NaN,NaN,NaN,NaN,3456.239287,908.568489,26.658844,37.486958,13.131971,388.960302,53.929016,4884.974866,NaN,NaN,NaN,NaN

In [4]:
def chg (x, change = change):
    for i in change:
        if change[i] == x:
            x = i
    return x

NameError: name 'change' is not defined

In [3]:
def fill_class_avto_regions(file, df, catts):
    
    df1 = df
    df1["Регион"] = df1["Регион"].apply(chg)
    df1["ФО"] = df1["ФО"].str.replace("ФО", "федеральный округ")
    df1["ФО"] = df1["ФО"].apply(chg)
    
    df1fo = df1[df1["Категория ТС"]==catts]
    df1fo = df1fo.groupby(["ФО"]).sum(numeric_only=True)
    
    df1reg = df1[df1["Категория ТС"]==catts]
    df1reg = df1reg.groupby(['Регион']).sum(numeric_only=True)
    
    df1rf = df1fo.reset_index()
    df1rf["Российская Федерация"] = "Российская Федерация"
    df1rf= df1rf.drop(columns = "ФО")
    df1rf = df1rf.groupby(["Российская Федерация"]).sum(numeric_only=True)
    
    ws = catts
    file2 = file
    report =  pd.read_excel(file2, sheet_name=ws, index_col=0, skiprows=1)
    report = check_col_name(report)
    
    for fo in df1fo.index:
        for col in df1fo:
            report.loc[fo, col] = df1fo.loc[fo, col]
    
    for reg in df1reg.index:
        for col in df1reg:
            report.loc[reg, col] = df1reg.loc[reg, col]
    
    for country in df1rf.index:
        for col in df1rf:
            report.loc[country, col] = df1rf.loc[country, col]  
    update_spreadsheet(file, report,  2, 3, catts)

In [2]:
def check_col_name (report):
    for name  in report.columns:
        if name == "СН4":
            report.rename(columns={name: "CH4"}, inplace =True)
    return report
        
import re 

def has_cyrillic(text):
    return bool(re.search('[а-яА-Я]', text))

In [507]:

def update_spreadsheet(path : str, _df, starcol : int = 1, startrow : int = 1, sheet_name : str ="ToUpdate"):
    '''
    
    :param path: Путь до файла Excel
    :param _df: Датафрейм Pandas для записи
    :param starcol: Стартовая колонка в таблице листа Excel, куда буду писать данные
    :param startrow: Стартовая строка в таблице листа Excel, куда буду писать данные
    :param sheet_name: Имя листа в таблице Excel, куда буду писать данные
    :return: 
    '''
    wb = ox.load_workbook(path)
    for row in wb[sheet_name]['B4:D300']:
        for cell in row:
            cell.value = None
    for ir in range(0, len(_df)):
        for ic in range(0, len(_df.iloc[ir])):
            wb[sheet_name].cell(startrow + ir, starcol + ic).value = _df.iloc[ir][ic]
    wb.save(path)

In [508]:
file = r'Выбросы_автотранспорта_по_виду_ТС.xlsx'
for catts in ox.load_workbook(file_loc).sheetnames:
    fill_class_avto_regions(file, df, catts)

In [509]:
# Чистим файл образец (исправляем ошибки с языком)

file_loc = r'Выбросы_автотранспорта_по_виду_ТС.xlsx'

ss = ox.load_workbook(file_loc)

for ss_name in ss.sheetnames:
    Newname = translit(ss_name, "ru", reversed=True)
    ss_sheet = ss.get_sheet_by_name(ss_name)
    ss_sheet.title = Newname
    ss.save(file_loc)

C:\Users\aleksandrov.vd\AppData\Local\Temp\ipykernel_20068\414800893.py:7: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  ss_sheet = ss.get_sheet_by_name(ss_name)